<a href="#"># Active</a><br />
<a href="#">Rules</a><br />
<a href="#">Staff</a><br />
<a href="#">GitHub</a><br />
<a href="#">News</a><br />
<a href="#">Patch Notes</a><br />
<a href="#">Discord</a>   <br />
<a href="#">Privacy Policy</a>   <br />
<a href="#">Terms of Service</a>   <br />
<a href="#">Report Bugs</a>   <br />
<a href="#">Suggestions</a>   <br />
<a href="#">Rankings</a>   <br />
<a href="#">Game Log</a>   <br />
<a href="#">Manual</a> <br />
