# .github/workflows/triage.yml
name: Auto-Triage Issues

on: [issues]

jobs:
  add_triage_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Priority Label and Add needs_triage
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
        with:
          script: |
            const issueLabels = context.payload.issue.labels.map(label => label.name);
            const hasPriority = issueLabels.some(label => label.endsWith('Priority'));

            if (!hasPriority) {
              console.log("No priority label found, adding needs_triage.");
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['needs_triage']
              });
            } else {
              console.log("Priority label found, skipping needs_triage.");
            }
